### ISSUE TITLE
It's owesome.But there is a bug in the demo.

### ISSUE THREAD

**Issue by lancewong2014** [xenione/SwipeLayout#4]
> `java.lang.IndexOutOfBoundsException: Invalid index 6, size is 6
                                                                                  at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                  at java.util.ArrayList.remove(ArrayList.java:403)
                                                                                  at apps.xenione.com.swipelayout.example.adapter.RightSwipeAdapter.deleteItem(RightSwipeAdapter.java:70)
……`
This bug is reproduceable,if you follow two steps.
1.Swip delete the item 5.
2.Before the item 5 dismiss,Quick swip dismiss item 6.

**Comment by xenione** [comment]
Thanks @lancewong2014 as you mentioned issue is in the app side so no effect on the library.  Bad approach to remove item since is done by position it should remove passing through the whole object instead I will change as soon as possible.

**Comment by xenione** [comment]
this issue from demo app is fixed no effect on swipe library so no new version library needed
